apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: felix-app
data:
  # Database Configuration
  DATABASE_CLIENT: postgres
  DATABASE_HOST: db
  DATABASE_PORT: "5432"
  DATABASE_NAME: "strapi"
  DATABASE_USERNAME: "strapi"
  
  # Strapi Backend Configuration
  HOST: "0.0.0.0"
  PORT: "1337"
  STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE: "de-DE"
  
  # Next.js Frontend Configuration
  SMTP_HOST: "smtp.strato.de"
  SMTP_PORT: "465"
  SMTP_USER: "no-reply@felix-nguyen.de"
  SMTP_FROM: "no-reply@felix-nguyen.de"
  COMPANY_EMAIL: "info@felix-nguyen.de"
  RECAPTCHA_SITE_KEY: "6Lf-YXUsAAAAAHtCvN_Q8CP-nO76E7ARiCpgUHS2"
